apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  namespace: standard
spec:
  selector:
    matchLabels:
      app: admin-deployment
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: admin-deployment
    spec:
      containers:
        - name: config-server
          image: springcommunity/spring-petclinic-cloud-admin-server
          ports:
            - containerPort: 9090
          resources:
            limits:
              memory: 512M
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: standard
spec:
  selector:
    app: admin-deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
