apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: standard
spec:
  selector:
    matchLabels:
      app: gateway-deployment
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway-deployment
    spec:
      containers:
        - name: config-server
          image: springcommunity/spring-petclinic-cloud-api-gateway
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512M
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: standard
spec:
  selector:
    app: gateway-deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
