apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
  namespace: standard
spec:
  selector:
    matchLabels:
      app: config-deployment
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: config-deployment
    spec:
      containers:
        - name: config-server
          image: springcommunity/spring-petclinic-cloud--config-server
          ports:
            - containerPort: 8888
          resources:
            limits:
              memory: 512M
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: standard
spec:
  selector:
    app: config-deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888


