apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  namespace: standard
spec:
  selector:
    matchLabels:
      app: customer-deployment
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: customer-deployment
    spec:
      containers:
        - name: customer-service
          image: springcommunity/spring-petclinic-cloud-customer-service
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: 512M
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: standard
spec:
  selector:
    app: customer-deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
