apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-deployment
  namespace: standard
spec:
  selector:
    matchLabels:
      app: vets-deployment
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vets-deployment
    spec:
      containers:
        - name: config-server
          image: springcommunity/spring-petclinic-cloud-vets-service
          ports:
            - containerPort: 8083
          resources:
            limits:
              memory: 512M
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
  namespace: standard
spec:
  selector:
    app: vets-deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
