apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-deployment
  namespace: standard
spec:
  selector:
    matchLabels:
      app: visits-deployment
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: visits-deployment
    spec:
      containers:
        - name: vets-service
          image: springcommunity/spring-petclinic-cloud--visits-service
          ports:
            - containerPort: 8082
          resources:
            limits:
              memory: 512M
---
apiVersion: v1
kind: Service
metadata:
  name: visit-service
  namespace: standard
spec:
  selector:
    app: visits-deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 8882
      targetPort: 8082
