name: Maven Build and Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4.1.1

  #   - name: Set up JDK 11
  #     uses: actions/setup-java@v3.13.0
  #     with:
  #       java-version: '11'
  #       distribution: 'adopt'
  #       cache: maven

  #   - name: Build with Maven
  #     run: mvn -B package --file pom.xml

  # test:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4.1.1

  #   - name: Set up JDK 11
  #     uses: actions/setup-java@v3.13.0
  #     with:
  #       java-version: '11'
  #       distribution: 'adopt'
  #       cache: maven

  #   - name: Run Tests with Maven
    
  #     run: mvn test --file pom.xml
      
  build-and-push:
    # needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up JDK 11
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_ID }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Set up Docker Repository Prefix
      run: echo "REPOSITORY_PREFIX=${{ secrets.DOCKERHUB_ID }}" >> $GITHUB_ENV
    
    # - name: Build and Push Docker Images
    #   run: mvn spring-boot:build-image -Pk8s -DREPOSITORY_PREFIX=${{ secrets.DOCKERHUB_ID }} && ./scripts/pushImages.sh
    
    - name: SSH into machine
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-known-hosts: ${{ secrets.SSH_HOST }}
        ssh-strict: true
        
    - name: Create Hello World file on remote machine
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no user@${{ secrets.SSH_HOST }} 'echo "hello world" > /hello.txt'

    - name: Configure Kubernetes CLI
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
        
    - name: Deploy to Kubernetes
      run: kubectl create secret generic wavefront -n spring-petclinic --from-literal=wavefront-url=https://wavefront.surf --from-literal=wavefront-api-token=2e41f7cf-1111-2222-3333-7397a56113ca
